### ISSUE TITLE
Render hang (hardware dependent)

### ISSUE THREAD

**Issue by LeMarwin** [tobbebex/GPipe-Core#21]
GPipe randomly hangs while rendering.
#### Source
https://github.com/Teaspot-Studio/gore-and-ash 
branch "norender" 
#### How to reproduce
* clone branch "norender"
* stack install
* run server: gore-and-ash-server 127.0.0.1 5556
* run client: gore-and-ash-client 127.0.0.1 5556
* run one more client instance *increases chance of hanging*
* just click or use arrows to move the square until the client hangs

#### Additional info 
* top shows that it's not a memory leak
* bug appeared on Intel's integrated graphics controller
* the bug is isolated to: gore-and-ash/testapp/src/client/Graphics.hs:107 "render $ rendering viewport"

**Comment by NCrashed** [comment]
I have related behavior on GeForce 840M, but instead of hang some frames are skipped (causing image "sticking"). The video driver prints following to console occasionally:
```
warning: dropping a frame to avoid deadlock
```

**Comment by tobbebex** [comment]
I noticed you are trying to [use VSync](https://github.com/Teaspot-Studio/gore-and-ash/blob/norender/testapp/src/client/Graphics.hs#L103), but that won't do anything since the thread you are on doesn't have the GL context current. GPipe-GLFW is actually having it current on another render thread (which is why you need threaded; strictly speaking it is GPipe-GLFW and not GPipe that requires it). Also see [this stackoverflow question](http://stackoverflow.com/questions/34624376/gpipe-vsync-fps). 

Without VSync, you will most likely end up in starvation of the threads, like @NCrashed experienced in plredmond/GPipe-GLFW#11. I am on windows myself which always enables VSync for windowed OpenGl, so that's why I haven't noticed it before.

Can you locally try out adding a call to `GLFW.swapInterval 1` right before [this line]( https://github.com/plredmond/GPipe-GLFW/blob/master/GPipe-GLFW/src/Graphics/GPipe/Context/GLFW.hs#L89) in GPipe-GLFW?

**Comment by LeMarwin** [comment]
I tried adding the line, but got no effect.

**Comment by tobbebex** [comment]
Do you have any other GLFW-based application to try multiple instances of? Just to rule out GLFW...

**Comment by LeMarwin** [comment]
I tried the example from here http://tobbebex.blogspot.ru/2015/09/gpipe-is-dead-long-live-gpipe.html and added scrolling to be sure.
The source is here: https://github.com/Teaspot-Studio/gpipe-test
It works just fine, no deadlocks.

**Comment by tobbebex** [comment]
Can't install it (even after `stack setup`):

```
\stack install
Setting codepage to UTF-8 (65001) to ensure correct output from GHC
Warning: C:\Users\Bexelius\git\Teaspot-Studio\gore-and-ash\stack.yaml: Unrecognized field in ProjectAndConfigMonoid: extra-package-dbs
GHC version mismatched, found 7.10.2 (x86_64), but expected version 7.10.3 (x86_64) (based on resolver setting in C:\Users\Bexelius\git\Teaspot-Studio\gore-and-ash\stack.yaml). Try running stack setup
```

Anyway, I saw that you are doing this:
```
win <- withContextWindow $ return . getGLFWWindow
```

`getGLFWWindow` comes from the `Graphics.GPipe.Context.GLFW.Unsafe` so I think you should start reviewing what you really do with the glfw window you get. Additionally, you return it from `withContextWindow` which is not really allowed as stated in its [documentation](https://hackage.haskell.org/package/GPipe-2.1.2/docs/Graphics-GPipe-Context.html#v:withContextWindow). GLFW has a lot of restrictions on what calls you may do when and where, e.g. some operations are only allowed from the main thread.

I am 99% certain that GPipe isn't at fault here anyway since it doesn't deal with threads at all, so I am going to close this issue until you can provide a more isolated repro of the issue. (That it hangs in `render $ rendering viewport` isn't really a proof given both that Haskell is lazy and that the `swapContextBuffers` call in there is dependent on what you do to GLFW before this). If anything, it could be due to a bug in GPipe-GLFW (that actually do have threads), but I doubt even that, given that the other simple example works and GPipe-GLFW doesn't really have that many different execution paths...
