### ISSUE TITLE
Avoiding the MonadIO constraint

### ISSUE THREAD

**Issue by LukaHorvat** [tobbebex/GPipe-Core#24]
I'm slightly bothered that there's a `MonadIO m` constraint on functions like `newBuffer`.
It means that a function that uses `newBuffer` has to be open to arbitrary side-effects.

Two ways of fixing this that come to mind is making the `ContextT` monad 'free-er' so it doesn't do anything directly and then just have the `MonadIO` constraint on the `runContextT` function that interprets the contextual actions into actual IO.

Another option would be to go for an MTL like approach and add a `MonadContext` class. Then make `ContextT` an instance of that class under a `MonadIO` constraint. Admittedly, I haven't really given it that much thought, but this option might actually be trivial to add. Just move the definition of `newBuffer` into the class and it's current implementation into the instance.

What do you think?

**Comment by tobbebex** [comment]
The only option to not have newBuffer require IO is to defer the actual opengl call to a later point. Since newBuffer may fail (e.g. if it is out of GPU memory) and/or may take some time to be performed by the graphics driver, we want those effects to be "observable" before other IO actions (indirectly) called by an action passed to lift in the ContextT m monad. However, there is no way to make lift require an IO constraint. 

So I rather keep the IO constraint on each GPipe action that calls out to opengl to make failureas and performance more predictable. But thanks for the feedback! :)
